import Images from "../images/index";
const cards = [
  {
    id: 1,
    title: "Boatman's Ride",
    poem: [
      "The Sun bounces off the water, but the soul is tranquil like the sky,",
      "Until romance births the barter of two smiles and a twinkle in her eye,",
      "The cold breeze flirts with two warm hearts as the boatman calls for a ride,",
      "She grabs my hand, looks deep in my eyes and whispers,",
      '"Love has no place to hide."',
    ],
    about: ["This is about Photo Number: "],
    image: Images.img_1,
  },
  {
    id: 2,
    title: "Morning Surprise",
    poem: [
      "The cold envelopes me, as I awake from the dreams of the day before,",
      "The room lit with a calming orange, reminds me of the sweater she wore,",
      "I make my way to the balcony, yawning, rubbing the sleep out of my eyes,",
      "The mountains! As my vision clears, I am spellbound and mesmerised,",
      "I had forgotten of my travels. What a Morning Surprise!",
    ],
    about: ["This is about Photo Number: "],
    image: Images.img_2,
  },
  {
    id: 3,
    title: "Patient Road",
    poem: [
      "Bursting through the door of the transit bus, to find a seat and a soul,",
      "A friend to keep you company as the journey gets quiet and cold,",
      "Someone who knows that the beauty of the mountains, only he can afford,",
      "Who pays his dues singing and wandering up the patient road.",
    ],
    about: ["This is about Photo Number: "],
    image: Images.img_3,
  },
  {
    id: 4,
    title: "No Signal.",
    poem: [
      "Yes, we are city boys, we find our way using our phones.",
      "Yes, our calm is noise, the peaceful streets have our minds blown.",
      "So we wander till we are lost hoping not to be found,",
      "Sometimes we like it with No Signal and nobody around.",
    ],
    about: ["This is about Photo Number: "],
    image: Images.img_4,
  },
  {
    id: 5,
    title: "Tourist-giri",
    poem: [
      "There's two kinds of folk, bundled together in a bus that leaves for the hills,",
      "Ones that shop to try and keep warm, others that challenge the Northern chills,",
      "Ones that flock to the churches, the promenades, and sometimes the zoo,",
      "Others that stumble into wrong rooms with fiery breath,",
      "For they have forgotten, Who is Who?",
    ],
    about: ["This is about Photo Number: "],
    image: Images.img_5,
  },
  {
    id: 6,
    title: "Amnesty",
    poem: ["Placeholder for Poem Number: "],
    about: ["This is about Photo Number: "],
    image: Images.img_6,
  },
  {
    id: 7,
    title: "Clement",
    poem: ["Placeholder for Poem Number: "],
    about: ["This is about Photo Number: "],
    image: Images.img_7,
  },
  {
    id: 8,
    title: "Tumult",
    poem: ["Placeholder for Poem Number: "],
    about: ["This is about Photo Number: "],
    image: Images.img_8,
  },
  {
    id: 9,
    title: "Bite.",
    poem: ["Placeholder for Poem Number: "],
    about: ["This is about Photo Number: "],
    image: Images.img_9,
  },
];
export default cards;
